server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/patientdb
    username: root
    password: ENSA2023
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PATIENT-SERVICE

  config:
    import: configserver:http://localhost:9296