apiVersion: apps/v1
kind: Deployment
metadata:
  name: = doctor-service-app
spec:
  selector:
    matchLabels:
      app: = doctor-service-app
  template:
    metadata:
      labels:
        app: = doctor-service-app
    spec:
      containers:
      - name: =
        image: sk09devops/pfs2023:doctorservice
        ports:
        - containerPort: 8084
        env:
          - name: EUREKA_SERVER_ADDRESS    
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
          - name: DB_HOST    
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service-svc
spec:
  selector:
    app: doctor-service-svc
  ports:
  - port: 80
    targetPort: 8084
