apiVersion: apps/v1
kind: Deployment
metadata:
  name: = patient-service-app
spec:
  selector:
    matchLabels:
      app: = patient-service-app
  template:
    metadata:
      labels:
        app: = patient-service-app
    spec:
      containers:
      - name: =
        image: pfs2023/patientservice
        ports:
        - containerPort: 8086
        env:
          - name: EUREKA_SERVER_ADDRESS    
            valueFrom:
              configMapKeyRef:
                key: eureka_service_address
                name: eureka-cm
          - name: DB_HOST    
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service-svc
spec:
  selector:
    app: patient-service-svc
  ports:
  - port: 80
    targetPort: 8086
