apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: sk09devops/pfs2023:serviceregistry
        ports:
        - containerPort: 8761
---
#headless service (internal)
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  clusterIP: None

  selector:
    app: myapp
  ports:
  - port: 8761
    targetPort: eureka
---
#Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  type: NodePort

  selector:
    app: eureka
  ports:
  - port: 80
    targetPort: 8761
